# Sets default memory used for gradle commands.
# Can be overridden by user or command line properties.

org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


# ============================================================
# PARCHMENT
# ============================================================

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17


# ============================================================
# ENVIRONMENT PROPERTIES
# ============================================================

minecraft_version=1.21.1

minecraft_version_range=[1.21.1]

neo_version=21.1.244

loader_version_range=[1,)


# ============================================================
# MAYMI MOD PROPERTIES
# ============================================================

# Identificador interno do mod.
# Deve ser igual ao valor utilizado em @Mod.
mod_id=maymi

# Nome exibido do mod.
mod_name=Maymi

# Licença do projeto.
mod_license=MIT

# Versão inicial do adaptador NeoForge.
mod_version=0.1.0

# Package base Java.
mod_group_id=br.com.maymi.neoforge

# Autor.
mod_authors=Joao Victor Souza

# Descrição.
mod_description=Integracao NeoForge da Maymi para servidores Minecraft.